use_frameworks!
platform :ios, '11.0'

target 'BottomKeyboardConstraint_Example' do
  pod 'BottomKeyboardConstraint', :path => '../'
  
  target 'BottomKeyboardConstraint_Tests' do
    inherit! :search_paths
    
  end
end
